#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_shop/shared/shared_types'


module ThriftShop
  module Auth
    class OauthToken
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ENTITY_UUID = 1
      ACCESS_TOKEN = 2
      REFRESH_TOKEN = 3
      AUTHORIZED_ROLES = 4
      ACCESS_TOKEN_EXPIRES_IN = 5
      REFRESH_TOKEN_EXPIRES_IN = 6

      FIELDS = {
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        ACCESS_TOKEN => {:type => ::Thrift::Types::STRING, :name => 'access_token'},
        REFRESH_TOKEN => {:type => ::Thrift::Types::STRING, :name => 'refresh_token'},
        AUTHORIZED_ROLES => {:type => ::Thrift::Types::LIST, :name => 'authorized_roles', :element => {:type => ::Thrift::Types::I32, :enum_class => ::ThriftShop::Shared::EntityRole}},
        ACCESS_TOKEN_EXPIRES_IN => {:type => ::Thrift::Types::I32, :name => 'access_token_expires_in'},
        REFRESH_TOKEN_EXPIRES_IN => {:type => ::Thrift::Types::I32, :name => 'refresh_token_expires_in'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class OauthTokens
      include ::Thrift::Struct, ::Thrift::Struct_Union
      OAUTH_TOKENS = 2

      FIELDS = {
        OAUTH_TOKENS => {:type => ::Thrift::Types::LIST, :name => 'oauth_tokens', :element => {:type => ::Thrift::Types::STRUCT, :class => ::ThriftShop::Auth::OauthToken}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CreateUserWebOauthTokensRequest
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ENTITY_UUIDS = 1
      REFRESH_TOKEN_LIFETIME = 2

      FIELDS = {
        ENTITY_UUIDS => {:type => ::Thrift::Types::LIST, :name => 'entity_uuids', :element => {:type => ::Thrift::Types::STRING}},
        REFRESH_TOKEN_LIFETIME => {:type => ::Thrift::Types::I32, :name => 'refresh_token_lifetime'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
