#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module ThriftShop
  module Contacts
    module ContactType
      EMAIL = 1
      FACEBOOK = 2
      PHONE_NUMBER = 3
      MANUAL = 4
      VALUE_MAP = {1 => "EMAIL", 2 => "FACEBOOK", 3 => "PHONE_NUMBER", 4 => "MANUAL"}
      VALID_VALUES = Set.new([EMAIL, FACEBOOK, PHONE_NUMBER, MANUAL]).freeze
    end

    class OnsiteContact
      include ::Thrift::Struct, ::Thrift::Struct_Union
      PROFILE_ID = 1
      CONTACT_TYPES = 2

      FIELDS = {
        PROFILE_ID => {:type => ::Thrift::Types::I32, :name => 'profile_id', :optional => true},
        CONTACT_TYPES => {:type => ::Thrift::Types::SET, :name => 'contact_types', :element => {:type => ::Thrift::Types::I32, :enum_class => ::ThriftShop::Contacts::ContactType}, :optional => true}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class OnsiteContactList
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ONSITE_CONTACTS = 1

      FIELDS = {
        ONSITE_CONTACTS => {:type => ::Thrift::Types::LIST, :name => 'onsite_contacts', :element => {:type => ::Thrift::Types::STRUCT, :class => ::ThriftShop::Contacts::OnsiteContact}, :optional => true}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
