#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_shop/shared/shared_types'
require 'thrift_shop/event_bus/eb_shared_types'


module ThriftShop
  module EventBus
    class CampaignCreated
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CAMPAIGN_UID = 1
      TOPIC_UIDS = 2

      FIELDS = {
        CAMPAIGN_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_uid'},
        TOPIC_UIDS => {:type => ::Thrift::Types::LIST, :name => 'topic_uids', :element => {:type => ::Thrift::Types::STRING}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CampaignDeleted
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CAMPAIGN_UID = 1

      FIELDS = {
        CAMPAIGN_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_uid'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CampaignUpdatedTopics
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CAMPAIGN_UID = 1
      TOPIC_UIDS = 2

      FIELDS = {
        CAMPAIGN_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_uid'},
        TOPIC_UIDS => {:type => ::Thrift::Types::LIST, :name => 'topic_uids', :element => {:type => ::Thrift::Types::STRING}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CampaignLaunched
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CAMPAIGN_UID = 1
      LAUNCHED_AT = 2

      FIELDS = {
        CAMPAIGN_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_uid'},
        LAUNCHED_AT => {:type => ::Thrift::Types::STRING, :name => 'launched_at'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CampaignUpdateCreated
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CAMPAIGN_UID = 1
      CAMPAIGN_UPDATE_UID = 2
      CAMPAIGN_LEADER_ENTITY_UUID = 3
      CAMPAIGN_TITLE = 4
      CAMPAIGN_UPDATE_TITLE = 5
      CAMPAIGN_UPDATE_BODY = 6
      IMAGE = 7
      VIDEO = 8

      FIELDS = {
        CAMPAIGN_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_uid'},
        CAMPAIGN_UPDATE_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_update_uid'},
        CAMPAIGN_LEADER_ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'campaign_leader_entity_uuid'},
        CAMPAIGN_TITLE => {:type => ::Thrift::Types::STRING, :name => 'campaign_title'},
        CAMPAIGN_UPDATE_TITLE => {:type => ::Thrift::Types::STRING, :name => 'campaign_update_title'},
        CAMPAIGN_UPDATE_BODY => {:type => ::Thrift::Types::STRING, :name => 'campaign_update_body'},
        IMAGE => {:type => ::Thrift::Types::STRING, :name => 'image', :optional => true},
        VIDEO => {:type => ::Thrift::Types::STRING, :name => 'video', :optional => true}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CampaignSupporterChanged
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CHANGE_TYPE = 1
      CAMPAIGN_UID = 2
      ENTITY_UUID = 3
      CHANGED_AT = 4

      FIELDS = {
        CHANGE_TYPE => {:type => ::Thrift::Types::I32, :name => 'change_type', :enum_class => ::ThriftShop::EventBus::ChangeType},
        CAMPAIGN_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_uid'},
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        CHANGED_AT => {:type => ::Thrift::Types::STRING, :name => 'changed_at'}
      }

      def struct_fields; FIELDS; end

      def validate
        unless @change_type.nil? || ::ThriftShop::EventBus::ChangeType::VALID_VALUES.include?(@change_type)
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Invalid value of field change_type!')
        end
      end

      ::Thrift::Struct.generate_accessors self
    end

    class CampaignPollTriggered
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CAMPAIGN_POLL_UID = 1

      FIELDS = {
        CAMPAIGN_POLL_UID => {:type => ::Thrift::Types::STRING, :name => 'campaign_poll_uid'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
