#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_shop/shared/shared_types'
require 'thrift_shop/contact_types/contact_types_types'
require 'thrift_shop/event_bus/eb_shared_types'


module ThriftShop
  module EventBus
    class ProfileCreated
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ENTITY_UUID = 1
      FULL_NAME = 2
      EMAIL_ADDRESS = 3
      CREATED_AT = 4
      AVATAR_URL = 5

      FIELDS = {
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        FULL_NAME => {:type => ::Thrift::Types::STRING, :name => 'full_name'},
        EMAIL_ADDRESS => {:type => ::Thrift::Types::STRING, :name => 'email_address'},
        CREATED_AT => {:type => ::Thrift::Types::STRING, :name => 'created_at'},
        AVATAR_URL => {:type => ::Thrift::Types::STRING, :name => 'avatar_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class ProfileUpdated
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ENTITY_UUID = 1
      FULL_NAME = 2
      EMAIL_ADDRESS = 3
      UPDATED_AT = 4
      AVATAR_URL = 5

      FIELDS = {
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        FULL_NAME => {:type => ::Thrift::Types::STRING, :name => 'full_name'},
        EMAIL_ADDRESS => {:type => ::Thrift::Types::STRING, :name => 'email_address'},
        UPDATED_AT => {:type => ::Thrift::Types::STRING, :name => 'updated_at'},
        AVATAR_URL => {:type => ::Thrift::Types::STRING, :name => 'avatar_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class ProfileDeleted
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ENTITY_UUID = 1
      DELETED_AT = 2

      FIELDS = {
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        DELETED_AT => {:type => ::Thrift::Types::STRING, :name => 'deleted_at'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class ProfileChanged
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CHANGE_TYPE = 1
      CHANGED_AT = 2
      ENTITY_UUID = 3
      FIRST_NAME = 4
      LAST_NAME = 5
      FULL_NAME = 6
      EMAIL_ADDRESS = 7
      AVATAR_URL = 8

      FIELDS = {
        CHANGE_TYPE => {:type => ::Thrift::Types::I32, :name => 'change_type', :enum_class => ::ThriftShop::EventBus::ChangeType},
        CHANGED_AT => {:type => ::Thrift::Types::STRING, :name => 'changed_at'},
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        FIRST_NAME => {:type => ::Thrift::Types::STRING, :name => 'first_name'},
        LAST_NAME => {:type => ::Thrift::Types::STRING, :name => 'last_name'},
        FULL_NAME => {:type => ::Thrift::Types::STRING, :name => 'full_name'},
        EMAIL_ADDRESS => {:type => ::Thrift::Types::STRING, :name => 'email_address'},
        AVATAR_URL => {:type => ::Thrift::Types::STRING, :name => 'avatar_url'}
      }

      def struct_fields; FIELDS; end

      def validate
        unless @change_type.nil? || ::ThriftShop::EventBus::ChangeType::VALID_VALUES.include?(@change_type)
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Invalid value of field change_type!')
        end
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
