#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_shop/shared/shared_types'
require 'thrift_shop/event_bus/eb_shared_types'


module ThriftShop
  module EventBus
    class ProfileDistrictChanged
      include ::Thrift::Struct, ::Thrift::Struct_Union
      CHANGE_TYPE = 1
      ENTITY_UUID = 2
      DISTRICT_UID = 3
      SOURCE_TYPE = 4
      SOURCE_UID = 5
      CHANGED_AT = 6

      FIELDS = {
        CHANGE_TYPE => {:type => ::Thrift::Types::I32, :name => 'change_type', :enum_class => ::ThriftShop::EventBus::ChangeType},
        ENTITY_UUID => {:type => ::Thrift::Types::STRING, :name => 'entity_uuid'},
        DISTRICT_UID => {:type => ::Thrift::Types::STRING, :name => 'district_uid'},
        SOURCE_TYPE => {:type => ::Thrift::Types::STRING, :name => 'source_type', :optional => true},
        SOURCE_UID => {:type => ::Thrift::Types::STRING, :name => 'source_uid'},
        CHANGED_AT => {:type => ::Thrift::Types::STRING, :name => 'changed_at'}
      }

      def struct_fields; FIELDS; end

      def validate
        unless @change_type.nil? || ::ThriftShop::EventBus::ChangeType::VALID_VALUES.include?(@change_type)
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Invalid value of field change_type!')
        end
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
