#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module ThriftShop
  module Device
    module PushProviderType
      APNS = 1
      FCM = 2
      VALUE_MAP = {1 => "APNS", 2 => "FCM"}
      VALID_VALUES = Set.new([APNS, FCM]).freeze
    end

  end
end
