#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module ThriftShop
  module ContactTypes
    class Location
      include ::Thrift::Struct, ::Thrift::Struct_Union
      LINE_1 = 1
      LINE_2 = 2
      CITY = 3
      REGION = 4
      COUNTRY = 5
      POSTAL_CODE = 6
      ISOCOUNTRYCODE = 7

      FIELDS = {
        LINE_1 => {:type => ::Thrift::Types::STRING, :name => 'line_1', :optional => true},
        LINE_2 => {:type => ::Thrift::Types::STRING, :name => 'line_2', :optional => true},
        CITY => {:type => ::Thrift::Types::STRING, :name => 'city'},
        REGION => {:type => ::Thrift::Types::STRING, :name => 'region'},
        COUNTRY => {:type => ::Thrift::Types::STRING, :name => 'country'},
        POSTAL_CODE => {:type => ::Thrift::Types::STRING, :name => 'postal_code', :optional => true},
        ISOCOUNTRYCODE => {:type => ::Thrift::Types::STRING, :name => 'isoCountryCode', :optional => true}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
