#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_shop/campaign_recommendation/campaign_recommendation_types'

module ThriftShop
  module CampaignRecommendation
  end
end
